services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    command: >
      sh -c "npm run start"
    ports:
      - ${EXPRESS_SERVER_PORT}:${EXPRESS_SERVER_PORT}
    env_file:
      - ./.env.public
    depends_on:
      - db
  db:
    restart: always
    image: postgres:16.4
    container_name: db
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    env_file:
      - ./.env.public
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:
    driver: local
