version: '3.8'

services:
    # ------------------------------------------------------api(expressjs)
    api:

    # ------------------------------------------------------db(mongodb)
    db:

    # ------------------------------------------------------other(volumes && networks)
volumes:

networks:
