version: '3.8'

services:
    # ------------------------------------------------------api(expressjs)
    api:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api
        command: >
            sh -c "npm run dev"
        ports:
            - ${SERVER_PORT_OUTER}:3000
        expose:
            - 3000
        networks:
            - backend
        links:
            - db
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://${SERVER_HOST}:3000/test']
            timeout: 5s
            interval: 10s
            retries: 3

    # ------------------------------------------------------db(mongodb)
    db:
        restart: always
        image: mysql:8.0
        container_name: db
        env_file:
            - .env
        ports:
            - ${DB_PORT_OUTER}:3306
        networks:
            - backend
        volumes:
            - ./db_data:/var/lib/mysql
            - ./simpleauth2_dump.sql:/docker-entrypoint-initdb.d/simpleauth2_dump.sql
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', '${DB_HOST}']
            timeout: 15s
            interval: 5s
            retries: 3

    # ------------------------------------------------------other(volumes && networks)
volumes:
    db_data:

networks:
    backend:
